config/routes.rb
Rails.application.routes.draw do
  resources :accounts
  # root to: "vehicles#index"
  root to: "homepage#index"

  resources :vehicles do
    resources :services
    resources :fill_ups
  end
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :vehicle
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]
  before_action :set_vehicle, only: [:index, :new, :edit, :show]

  # GET /services
  # GET /services.json
  def index
    @services = @vehicle.services
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    def set_vehicle
      @vehicle = Vehicle.find(params[:vehicle_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.fetch(:service, {})
    end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
<%= form_with(model: [:vehicle, service], local: true) do |form| %>
  <% if service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% service.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  to be a drop down menu
  <div class="field">
    <%= form.label :service_type %><br>
    <%= form.number_field :service_type %>
  </div>

  <div class="field">
    <%= form.label :odometer_reading %><br>
    <%= form.number_field :odometer_reading %>
  </div>

  <div class="field">
    <%= form.label :total_cost %><br>
    <%= form.number_field :total_cost %>
  </div>

  <div class="field">
    <%= form.label :notes %><br>
    <%= form.text_field :notes %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/services/edit.html.erb
<h1>Editing Service</h1>

<%= render 'form', service: @service %>

<%= link_to 'Show', [@vehicle, @service] %> |
<%= link_to 'Back', vehicle_services_path %>

app/views/services/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Services</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @services.each do |service| %>
      <tr>
        <td><%= link_to 'Show', vehicle_service_path(@vehicle, service) %></td>
        <td><%= link_to 'Edit', edit_vehicle_service_path(@vehicle, service) %></td>
        <td><%= link_to 'Destroy', vehicle_service_path(@vehicle, service), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Service', new_vehicle_service_path(@vehicle) %> |
<%= link_to 'Back', vehicle_path(@vehicle) %>

app/views/services/new.html.erb
<h1>New Service</h1>

<%= render 'form', service: @service %>

<%= link_to 'Back', vehicle_services_path(@vehicle) %>

app/views/services/show.html.erb
<p id="notice"><%= notice %></p>

<h5><%= @vehicle.nickname %></h5>
<p>Service details</p>
  <ul class="no_bullets">
    <li>Date: <%= @service.updated_at %></li>
    <li>Type: <%= @service.service_type %></li>
    <li>Odometer Reading: <%= @service.odometer_reading %></li>
    <li>Total Cost for Service: <%= @service.total_cost %></li>
    <li>NOTES: <%= @service.notes %></li>
  </ul>

  <h5>Average MPG: <%= %></h5>
  <h5>Average MPG of a bicycle 178 *</h5>

<%= link_to 'Edit', edit_vehicle_service_path(@vehicle, @service) %> |
<%= link_to 'Back', vehicle_services_path %>