config/routes.rb
Rails.application.routes.draw do
  resources :accounts
  # root to: "vehicles#index"
  root to: "homepage#index"

  resources :vehicles do
    resources :services
    resources :fill_ups
  end
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/fill_up.rb
class FillUp < ApplicationRecord
  belongs_to :vehicle

  # before_save :calculate_mpg
  def calculate_mpg(vehicle)
    previous_fill_up_mileage = vehicle.fill_ups.last.odometer_reading
    mileage_difference = odometer_reading - previous_fill_up_mileage
    current_mpg = mileage_difference.to_f / gallons_in_fill
    mpg = current_mpg
  end

end

app/controllers/fill_ups_controller.rb
class FillUpsController < ApplicationController
  before_action :set_fill_up, only: [:show, :edit, :update, :destroy]
  before_action :set_vehicle, only: [:index, :new, :edit, :show, :create, :update]

  # GET /fill_ups
  # GET /fill_ups.json
  def index
    @fill_ups = @vehicle.fill_ups.order(:created_at)
    # if NO fillups all going to exist get rid of this.
  end

  # GET /fill_ups/1
  # GET /fill_ups/1.json
  def show
  end

  # GET /fill_ups/new
  def new
    @fill_up = FillUp.new
  end

  # GET /fill_ups/1/edit
  def edit
  end

  # POST /fill_ups
  # POST /fill_ups.json
  def create
    #calculate_mpg and calculate_total_costs methods defined below and called here.
    @fill_up = FillUp.new(fill_up_params)
    @fill_up.calculate_mpg(@vehicle)

    #calculate current total, something here is not quite right yet.  Need to fix decimals and rounding
    @fill_up.total_cost = @fill_up.price_per_gallon * @fill_up.gallons_in_fill

    #running total
    # previous_fill_up_total = @vehicle.fillups.last.

    if @fill_up.save
      redirect_to vehicle_fill_up_path(@vehicle, @fill_up), notice: 'Fill up was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /fill_ups/1
  # PATCH/PUT /fill_ups/1.json
  def update
    if @fill_up.update(fill_up_params)
      redirect_to vehicle_fill_up_path(@vehicle, @fill_up), notice: 'Fill up was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /fill_ups/1
  # DELETE /fill_ups/1.json
  def destroy
    if @fill_up.destroy
      redirect_to fill_ups_url, notice: 'Fill up was successfully destroyed.'
    end
  end



  private
  # Use callbacks to share common setup or constraints between actions.
  def set_fill_up
    @fill_up = FillUp.find(params[:id])
  end

  def set_vehicle
    @vehicle = Vehicle.find(params[:vehicle_id])
  end

  def fill_up_params
    params.require(:fill_up).permit(:odometer_reading, :price_per_gallon, :gallons_in_fill, :total_cost, :percent_city_highway, :notes)
  end
end

app/helpers/fill_ups_helper.rb
module FillUpsHelper
end

app/views/fill_ups/_form.html.erb
<%= form_with(model: [@vehicle, fill_up], local: true) do |form| %>
  <% if fill_up.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fill_up.errors.count, "error") %> prohibited this fill_up from being saved:</h2>

      <ul>
      <% fill_up.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :odometer_reading %><br>
    <%= form.number_field :odometer_reading %>
  </div>

  <div class="field">
    <%= form.label :price_per_gallon %><br>
    <%= form.number_field :price_per_gallon %>
  </div>

  <div class="field">
    <%= form.label :gallons_in_fill %><br>
    <%= form.number_field :gallons_in_fill %>
  </div>

  <div class="field">
    <%= form.label :total_cost %><br>
    <%= form.number_field :total_cost %>
  </div>

  <div class="field">
    <%= form.label :percent_city_highway %><br>
    <%= form.number_field :percent_city_highway %>
  </div>

  <div class="field">
    <%= form.label :notes %><br>
    <%= form.text_field :notes %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/fill_ups/edit.html.erb
<h1>Editing Fill Up</h1>

<%= render 'form', fill_up: @fill_up %>

<%= link_to 'Show', [@vehicle, @fill_up] %> |
<%= link_to 'Back', vehicle_fill_ups_path %>

app/views/fill_ups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fill Ups</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fill_ups.each do |fill_up| %>
      <tr>
        <td><%= link_to 'Show', vehicle_fill_up_path(@vehicle, fill_up) %></td>
        <td><%= link_to 'Edit', edit_vehicle_fill_up_path(@vehicle, fill_up) %></td>
        <td><%= link_to 'Destroy', vehicle_fill_up_path(@vehicle, fill_up), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fill Up', new_vehicle_fill_up_path(@vehicle) %> |
<%= link_to 'Back', vehicle_path(@vehicle) %>

app/views/fill_ups/new.html.erb
<h1>New Fill Up</h1>

<%= render 'form', fill_up: @fill_up %>

<%= link_to 'Back', vehicle_fill_ups_path(@vehicle) %>

app/views/fill_ups/show.html.erb
<p id="notice"><%= notice %></p>

<h5><%= @vehicle.nickname %></h5>
<p>Fill Up details</p>
  <ul class="no_bullets">
    <li>Date: <%= @fill_up.updated_at %></li>
    <li>MPG: <%= @fill_up.mpg %></li>
    <li>Odometer Reading: <%= @fill_up.odometer_reading %></li>
    <li>Price Per Gallon: <%= @fill_up.price_per_gallon %></li>
    <li>Gallons in Fuel Up: <%= @fill_up.gallons_in_fill %></li>
    <li>Fuel Up Cost: <%= @fill_up.total_cost %></li>
    <li>City(0) vs. Highway Driving(100): <%= @fill_up.percent_city_highway %></li>
    <li>NOTES: <%= @fill_up.notes %></li>
  </ul>

  <h5>Average MPG: <%= @vehicle.average_mpg %></h5>
  <h5>Average MPG of a bicycle 178 *</h5>
  <h5>Total Costs of Fuel: $<%= @vehicle.lifetime_cost_of_fuel  %></h5>

<%= link_to 'Edit', edit_vehicle_fill_up_path(@vehicle, @fill_up) %> |
<%= link_to 'Back', vehicle_fill_ups_path %>