config/routes.rb
Rails.application.routes.draw do
  resources :accounts
  # root to: "vehicles#index"
  root to: "homepage#index"

  resources :vehicles do
    resources :services
    resources :fill_ups
  end
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  has_many :accounts, dependent: :destroy
  has_many :users, through: :accounts
  has_many :fill_ups
  has_many :services

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  def average_mpg
    array_of_mpgs = []
    fill_ups.each do |fill_up|
      next if fill_up.mpg.nil?
      array_of_mpgs.push(fill_up.mpg)
    end
    array_of_mpgs.sum.to_f / array_of_mpgs.length
  end
  #in instance you will be calling an existing @vehicle.average_mpg

  def lifetime_cost_of_fuel
    array_of_costs = []
    fill_ups.each do |fill_up|
      next if fill_up.total_cost.nil?
      array_of_costs.push(fill_up.total_cost)
    end
    array_of_costs.sum.to_f
  end

  def latest_fill_up_odometer
    array_of_odometer_readings = []
    fill_ups.each do |fill_up|
      next if fill_up.total_cost.nil?
      array_of_odometer_readings.push(fill_up.odometer_reading)
    end
    array_of_odometer_readings.last
  end

end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]

  # GET /vehicles
  # GET /vehicles.json
  def index
    @vehicles = current_user.vehicles
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
  end

  # GET /vehicles/new
  def new
    @vehicle = current_user.vehicles.new
  end

  # GET /vehicles/1/edit
  def edit
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)
    if @vehicle.save
      assign_vehicle_to_user
      redirect_to @vehicle, notice: 'Vehicle was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /vehicles/1
  # PATCH/PUT /vehicles/1.json
  def update
    if @vehicle.update(vehicle_params)
      redirect_to @vehicle, notice: 'Vehicle was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    if @vehicle.destroy
      redirect_to vehicles_url, notice: 'Vehicle was successfully destroyed.'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = current_user.vehicles.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_params
      params.require(:vehicle).permit(:nickname, :year, :make, :model)
        # , :odometer, :image)
        # , :trim
        #anything that comes from the actual form
    end

    def assign_vehicle_to_user
      Account.create(
        user_id: current_user.id,
        vehicle_id: @vehicle.id
      )
      #need to research how to properly integrate this into a :through, this is the hacky version, if I were to delete a vehicle now the account record still exists in the database.
    end
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/vehicles/_form.html.erb
<%= form_with(model: vehicle, local: true) do |form| %>
  <% if vehicle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
      <% vehicle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nickname %><br>
    <%= form.text_field :nickname %>
  </div>

  <div class="field">
    <%= form.label :image %><br>
    <%= form.file_field :image %>
  </div><br>

<%= form.select :year, options_for_select((1950..(Time.now.year + 1)).to_a.reverse, selected: @vehicle.year), include_blank: 'Year' %>

<%= form.select :make, options_for_select([["Acura", "Acura"], ["Aston Martin", "Aston Martin"], ["Audi", "Audi"], ["Bentley", "Bentley"], ["BMW", "BMW"], ["Buick", "Buick"], ["Cadillac", "Cadillac"]], selected: @vehicle.make), include_blank: 'Make' %>

<%= form.select :model, options_for_select([["Crosstrek", "Crosstrek"], ["Forester", "Forester"], ["Impreza", "Impreza"], ["Legacy", "Legacy"], ["Outback", "Outback"], ["WRX", "WRX"]], selected: @vehicle.model), include_blank: 'Model' %><br><br>
 <!-- class="chzn-select year" style="width:70px;" tabindex="1" -->

 <div class="field">
   <%= form.label :odometer %><br>
   <%= form.text_field :odometer %>
 </div>

  <div class="actions">
    <%= form.submit %>
  </div><br>

  <p>To add a service or fill up to a new vehicle click on it in your list after it has been created.</p>

<% end %>

app/views/vehicles/edit.html.erb
<h1>Editing Vehicle</h1>

<%= render 'form', vehicle: @vehicle %>

<%= link_to 'Show', @vehicle %> |
<%= link_to 'Back', vehicles_path %>

app/views/vehicles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vehicles</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vehicles.each do |vehicle| %>
      <tr>
        <td><%= link_to vehicle.nickname, vehicle %>&nbsp;&nbsp;&nbsp;&nbsp;</td>
        <td><%= link_to 'Edit', edit_vehicle_path(vehicle) %> |&nbsp;</td>
        <td><%= link_to 'Destroy', vehicle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vehicle', new_vehicle_path %>

app/views/vehicles/new.html.erb
<h1>New Vehicle</h1>

<%= render 'form', vehicle: @vehicle %>

<%= link_to 'Back', vehicles_path %>

app/views/vehicles/show.html.erb
<p id="notice"><%= notice %></p>
<%= image_tag("#{@vehicle.image}", :class => "rounded_corners") %><br>
<div class="row">
  <div class="col-md-4">
    <h5><%= @vehicle.nickname %></h5>
    <ul class="no_bullets">
      <li>Year: <%= @vehicle.year %></li>
      <li>Make: <%= @vehicle.make %></li>
      <li>Model: <%= @vehicle.model %></li>
      <li>Mileage: <%= @vehicle.latest_fill_up_odometer %></li>
      <li>Notes: <%= @vehicle.notes %></li>
    </ul>

    <h5>Average MPG: <%= @vehicle.average_mpg %></h5>
    <h5>Average MPG of a bicycle 178 *</h5>
    <h5>Total Costs of Fuel: $<%= @vehicle.lifetime_cost_of_fuel %></h5>

    <%= link_to 'Edit Vihicle', edit_vehicle_path(@vehicle) %>
  </div>
  <div class="col-md-4">
    <h5>Fill Ups</h5>
    <% @vehicle.fill_ups.each do |fill_up| %>
      <ul>
        <li><%= link_to vehicle_fill_up_path(@vehicle, fill_up) do %>
              <%= fill_up.created_at.strftime("%F") %>
            <% end %>&nbsp;&nbsp;
          <%= link_to 'Edit', edit_vehicle_fill_up_path(@vehicle, fill_up) %> |&nbsp;
          <%= link_to 'Destroy', vehicle_fill_up_path(@vehicle, fill_up), method: :delete, data: { confirm: 'Are you sure?' } %></li>
      </ul>
    <% end %>
    <%= link_to 'Create new Fill Up', new_vehicle_fill_up_path(@vehicle) %>
  </div>
  <div class="col-md-4">
    <h5>Servies</h5>
    <% @vehicle.services.each do |service| %>
    <ul>
      <li><%= link_to vehicle_service_path(@vehicle, service) do %>
            <%= service.created_at.strftime("%F") %>
          <% end %>&nbsp;&nbsp;
        <%= link_to 'Edit', edit_vehicle_service_path(@vehicle, service) %> |&nbsp;
        <%= link_to 'Destroy', vehicle_service_path(@vehicle, service), method: :delete, data: { confirm: 'Are you sure?' } %></li>
    </ul>
    <% end %>

    <%= link_to 'Create new Service', new_vehicle_service_path(@vehicle) %>

  </div>

</div>

<hr>

<%= link_to 'Back To Vehicles', vehicles_path %>